#!/bin/bash

javac ./src/Main.java -cp ./src -d ./bin

# TO RUN
# add the generatecert inside bin: bin->script->generatecert  
# $ cd bin
# $ java Main

# All this to RUN THIS
# java -Djavax.net.debug=ssl:handshake Main
# java -Djavax.net.debug=ssl:handshake:verbose:keymanager:trustmanager -Djava.security.debug=access:stack Main

# future things
# jar options jar-file [manifest-file] class-files...
# jar -cfvem Server ./script/manifest ./bin/Main.class